LogTime yes
Foreground yes
LocalSocket /tmp/clamd.sock
LocalSocketGroup clamav
LocalSocketMode 660
TCPSocket 3310
TCPAddr 0.0.0.0
MaxFileSize 25M
MaxScanSize 100M
StreamMaxLength 25M
MaxThreads 4
ExcludePath ^/proc/
ExcludePath ^/sys/
