clamav {
  type = "clamav";
  servers = "clamav:3310";
  symbol = "CLAM_VIRUS";
  action = "reject";
  message = "Message contains malware (${VIRUS})";
  scan_mime_parts = true;
  scan_text_mime = false;
  max_size = 20971520;
  retransmits = 2;
  timeout = 30;
}
