class CONFIG_KEYS:
    OUTGOING_ATTACHMENT_MAX_SIZE_MB = "OUTGOING_ATTACHMENT_MAX_SIZE_MB"
    INCOMING_ATTACHMENT_MAX_SIZE_MB = "INCOMING_ATTACHMENT_MAX_SIZE_MB"
    ATTACHMENT_RETENTION_HOURS = "ATTACHMENT_RETENTION_HOURS"


class CONFIG_LIMITS:
    OUTGOING_ATTACHMENT_MAX_SIZE_MB_MIN = 1
    OUTGOING_ATTACHMENT_MAX_SIZE_MB_MAX = 1
    INCOMING_ATTACHMENT_MAX_SIZE_MB_MIN = 1
    INCOMING_ATTACHMENT_MAX_SIZE_MB_MAX = 5
    ATTACHMENT_RETENTION_HOURS_MIN = 1
    ATTACHMENT_RETENTION_HOURS_MAX = 48

    RANGES = {
        CONFIG_KEYS.OUTGOING_ATTACHMENT_MAX_SIZE_MB: (OUTGOING_ATTACHMENT_MAX_SIZE_MB_MIN, OUTGOING_ATTACHMENT_MAX_SIZE_MB_MAX),
        CONFIG_KEYS.INCOMING_ATTACHMENT_MAX_SIZE_MB: (INCOMING_ATTACHMENT_MAX_SIZE_MB_MIN, INCOMING_ATTACHMENT_MAX_SIZE_MB_MAX),
        CONFIG_KEYS.ATTACHMENT_RETENTION_HOURS: (ATTACHMENT_RETENTION_HOURS_MIN, ATTACHMENT_RETENTION_HOURS_MAX),
    }


class CONFIG_FIELDS:
    NAMES = {
        "outgoing_attachment_max_size_mb": CONFIG_KEYS.OUTGOING_ATTACHMENT_MAX_SIZE_MB,
        "incoming_attachment_max_size_mb": CONFIG_KEYS.INCOMING_ATTACHMENT_MAX_SIZE_MB,
        "attachment_retention_hours": CONFIG_KEYS.ATTACHMENT_RETENTION_HOURS,
    }


class CONFIG_DEFAULTS:
    VALUES = [{"key": CONFIG_KEYS.OUTGOING_ATTACHMENT_MAX_SIZE_MB, "value": 1, "value_type": "integer"}, {"key": CONFIG_KEYS.INCOMING_ATTACHMENT_MAX_SIZE_MB, "value": 5, "value_type": "integer"}, {"key": CONFIG_KEYS.ATTACHMENT_RETENTION_HOURS, "value": 48, "value_type": "integer"}]
