proxy_pass http://$app_backend;
proxy_request_buffering on;
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto https;
proxy_pass_request_headers on;
proxy_intercept_errors off;
proxy_hide_header X-Powered-By;
proxy_hide_header Server;
include /etc/nginx/orion/security-headers.conf;
add_header Cache-Control "no-store, no-cache, must-revalidate" always;
