name: Codacy Security Scan

on:
  push:
    branches:
      - trusted-main
      - main
  pull_request:
    branches:
      - trusted-main
  schedule:
    - cron: '33 6 * * 2'

permissions: read-all

jobs:
  codacy-security-scan:
    runs-on: ubuntu-latest
    name: Codacy Security Scan
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up JDK
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run Codacy Analysis for GitHub Code Scanning
        uses: codacy/codacy-analysis-cli-action@562ee3e92b8e92df8b67e0a5ff8aa8e261919c08 # v4.4.7
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          verbose: true
          output: results.sarif
          format: sarif
          gh-code-scanning-compat: true
          max-allowed-issues: 2147483647

      - name: Split SARIF runs into unique categories
        run: python3 .github/scripts/split-sarif.py

      - name: Upload SARIF results to GitHub batch 01
        if: ${{ hashFiles('sarif-results-01/*.sarif') != '' }}
        uses: github/codeql-action/upload-sarif@db488ddef3bf6cb639b32c2e9a7c0a7ea8271d28 # v4.37.8
        with:
          sarif_file: sarif-results-01
